controllers/ComprasController.php
<?php

namespace app\controllers;

use app\models\compras;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * ComprasController implements the CRUD actions for compras model.
 */
class ComprasController extends Controller
{
    /**
     * @inheritDoc
     */
    public function behaviors()
    {
        return array_merge(
            parent::behaviors(),
            [
                'verbs' => [
                    'class' => VerbFilter::className(),
                    'actions' => [
                        'delete' => ['POST'],
                    ],
                ],
            ]
        );
    }

    /**
     * Lists all compras models.
     *
     * @return string
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => compras::find(),
            /*
            'pagination' => [
                'pageSize' => 50
            ],
            'sort' => [
                'defaultOrder' => [
                    'codigocompras' => SORT_DESC,
                ]
            ],
            */
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single compras model.
     * @param int $codigocompras Codigocompras
     * @return string
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($codigocompras)
    {
        return $this->render('view', [
            'model' => $this->findModel($codigocompras),
        ]);
    }

    /**
     * Creates a new compras model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return string|\yii\web\Response
     */
    public function actionCreate()
    {
        $model = new compras();

        if ($this->request->isPost) {
            if ($model->load($this->request->post()) && $model->save()) {
                return $this->redirect(['view', 'codigocompras' => $model->codigocompras]);
            }
        } else {
            $model->loadDefaultValues();
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing compras model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param int $codigocompras Codigocompras
     * @return string|\yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($codigocompras)
    {
        $model = $this->findModel($codigocompras);

        if ($this->request->isPost && $model->load($this->request->post()) && $model->save()) {
            return $this->redirect(['view', 'codigocompras' => $model->codigocompras]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing compras model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param int $codigocompras Codigocompras
     * @return \yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($codigocompras)
    {
        $this->findModel($codigocompras)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the compras model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param int $codigocompras Codigocompras
     * @return compras the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($codigocompras)
    {
        if (($model = compras::findOne(['codigocompras' => $codigocompras])) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use yii\data\ActiveDataProvider;
use app\models\productos;
use kartik\alert\Alert;
use yii\db\Expression;
use app\models\Compras;
class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    
    

    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {        
     
         return $this->render('index');     
    }
   
     public function actionReglasstock2(){
        
        
        $numero = Yii::$app->db
                ->createCommand("SELECT cantidad FROM productos WHERE 'nombre' = 'paco'")
                ->queryScalar();
        
        $cantidadmin = Yii::$app->db
                ->createCommand("SELECT cantidadmin FROM productos WHERE 'nombre' = 'paco'")
                ->queryScalar();
          
         if (($numero) <$cantidadmin){
         echo 
         $this->render('alertas');

      } else{
            return $this->render('index');     
      }
    
    }
    
      public function actionReglasstock3(){
        
         $cantidadmin = Yii::$app->db
                ->createCommand("SELECT COUNT(*) FROM productos WHERE cantidad < cantidadmin")
                ->queryScalar();
          
         if ($cantidadmin > 0) { 
          
          
      $dataProvider = new ActiveDataProvider([
            'query'=> Productos::find()
                   ->select("nombre, codigoproveedorf")
                   ->distinct()
                   ->where("cantidad < cantidadmin"),
                   
        ]);
        
        return $this->render("alertas",[
            "resultados"=>$dataProvider,
            "campos"=>['Nombre, Proveedor '],
            "titulo"=>"Nos falta Stock en estos productos",
            "enunciado"=>"Consulta con los proveedores",
            
        ]);
         } else {
           return $this->render('nostock');  
         }
    }
    
    

     public function actionManual()
    {
        return $this->render('manual');
        
    }
    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }

        $model->password = '';
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        return $this->render('about');
    }
    
     public function actionGestion()
    {
        return $this->render('gestion');
    }
    
    public function actionCdd()
    {
        $grafCategoria = $this->grafCategoria();
        $ventasPormes = $this->ventasPormes();
        $grafEmbajadores = $this->grafEmbajadores();
         return $this->render('cdd',[
            'grafCategoria'=>$grafCategoria,
            'ventasPormes'=>$ventasPormes,
            'grafEmbajadores'=>$grafEmbajadores,           
        ]);

    }
    
    public function ventasPormes(){
        $expresion = new Expression("select COUNT(*) as cantidad, elt(MONTH(fecha),'Enero','Febrero','Marzo','Abril','Mayo','Junio','Julio','Agosto','Septiembre','Octubre','Noviembre','Diciembre') as mes, year(fecha) as year from compras group by mes, year order by fecha asc limit 12");
        $query = Yii::$app->db->createCommand($expresion)->queryAll();
        return $query;
    }
    
     public function grafEmbajadores(){
        $expresion = new Expression("select numeroventas, numeroregistros, nombre as nombre2 from embajadores");
        $query = Yii::$app->db->createCommand($expresion)->queryAll();
        return $query;
    }
    
    
    
    public function grafCategoria(){
        $expresion = new Expression("select COUNT(codigoproductosf) cantidad2, nombre from compras LEFT JOIN productos ON compras.codigoproductosf = productos.codigoproductos GROUP BY codigoproductosf order by cantidad2 desc");
        $query = Yii::$app->db->createCommand($expresion)->queryAll();
        return $query;
    }


    
    
    
}

controllers/TiposController.php
<?php

namespace app\controllers;

use app\models\tipos;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * TiposController implements the CRUD actions for tipos model.
 */
class TiposController extends Controller
{
    /**
     * @inheritDoc
     */
    public function behaviors()
    {
        return array_merge(
            parent::behaviors(),
            [
                'verbs' => [
                    'class' => VerbFilter::className(),
                    'actions' => [
                        'delete' => ['POST'],
                    ],
                ],
            ]
        );
    }

    /**
     * Lists all tipos models.
     *
     * @return string
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => tipos::find(),
            /*
            'pagination' => [
                'pageSize' => 50
            ],
            'sort' => [
                'defaultOrder' => [
                    'codigotipos' => SORT_DESC,
                ]
            ],
            */
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single tipos model.
     * @param int $codigotipos Codigotipos
     * @return string
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($codigotipos)
    {
        return $this->render('view', [
            'model' => $this->findModel($codigotipos),
        ]);
    }

    /**
     * Creates a new tipos model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return string|\yii\web\Response
     */
    public function actionCreate()
    {
        $model = new tipos();

        if ($this->request->isPost) {
            if ($model->load($this->request->post()) && $model->save()) {
                return $this->redirect(['view', 'codigotipos' => $model->codigotipos]);
            }
        } else {
            $model->loadDefaultValues();
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing tipos model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param int $codigotipos Codigotipos
     * @return string|\yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($codigotipos)
    {
        $model = $this->findModel($codigotipos);

        if ($this->request->isPost && $model->load($this->request->post()) && $model->save()) {
            return $this->redirect(['view', 'codigotipos' => $model->codigotipos]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing tipos model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param int $codigotipos Codigotipos
     * @return \yii\web\Response
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($codigotipos)
    {
        $this->findModel($codigotipos)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the tipos model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param int $codigotipos Codigotipos
     * @return tipos the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($codigotipos)
    {
        if (($model = tipos::findOne(['codigotipos' => $codigotipos])) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        This is the About page. You may modify the following file to customize its content:
    </p>

    <code><?= __FILE__ ?></code>
</div>

views/site/ads.php
<?php
$this->title = 'ADS';
?>

<div>
    
 
</div>

views/site/alertas.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;
//use module\user\assets\UserAsset;
use yii\widgets\DetailView;


$this->title = 'Stock';
        ?>
 <div class="card4 flex-shrink-0 coloresletrablanca ">
             
                <h6 class="separator">
                    
                    Necesitamos Stock en estos productos:
                </h6>
 
        </div>

<div class="separator table">
    
</div>

<div class="">
    <div class="">   
 
    </div>
<?=GridView::widget([
    'dataProvider' => $resultados,
     'columns' => [ 
            ['class' => 'yii\grid\SerialColumn'],
            'nombre',
            ['class' => 'yii\grid\ActionColumn',
                'header' => 'Proveedores',
                'template' => '{proveedores}',
                'buttons' => [
                    'proveedores' => function($url, $model) {
                        return Html::a('Ir al proveedor', ['proveedores/view', 'codigoproveedores' => $model['codigoproveedorf']], ['class'=>'btn btn-success']);
                }
                ],
             ],
         ],
    'layout' => "\n{items}\n{pager}",
   // 'tableOptions' => ['class' => '']
]); ?>
</div>

views/site/cdd.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use coderius\swiperslider\SwiperSlider;
use miloschuman\highcharts\Highcharts;
use yii\web\JsExpression;
/* @var $this yii\web\View */

$this->title = 'Centro de datos';
?>
<div class="row">
    <div class="col-md-6">
 <?=
    Highcharts::widget([
    'scripts' => [
        'modules/exporting',
        'themes/grid-light',
    ],
    'options' => [
        'title' => [
            'text' => 'Trafico en Tienda Online',
        ],
        'xAxis' => [
            'categories' => ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo'],
        ],
        'labels' => [
            'items' => [
                [
                    'html' => 'Afluencia usuarios',
                    'style' => [
                        'left' => '50px',
                        'top' => '18px',
                        'color' => new JsExpression('(Highcharts.theme && Highcharts.theme.textColor) || "black"'),
                    ],
                ],
            ],
        ],
        'series' => [
            
            [
                'type' => 'spline',
                'name' => 'INGRESOS',
                'data' => [100, 150, 122, 145, 323],
                'marker' => [
                    'lineWidth' => 5,
                    'lineColor' => new JsExpression('Highcharts.getOptions().colors[3]'),
                    'fillColor' => 'white',
                ],
            ],         
        ],
    ]
]);
?>
        </div>
    <div class="col-md-6">
     <?php   
    foreach($ventasPormes as $values){
                        $mes[] = ($values['mes']);
                        $cantidad[] = intval($values['cantidad']);
                    }
                    echo
                    Highcharts::widget([
                        'scripts' => ['modules'],
                        'options' => [
                            'chart' => ['type' => 'column'],
                            'title' => ['text' => 'Ventas'],
                            'xAxis' => ['categories' => $mes],
                            'yAxis' => ['title' => ['text' => 'Cantidad']],
                            'series' => [
                                [
                                   'name' => 'Ventas',
                                   'color' => 'orange',
                                   'colorByPoint' => false,
                                   'data' => $cantidad,
                                ],
                            ],
                        ],
                    ]);
?>
        </div>
    <div class="col-md-6">
      <?php
    foreach($grafCategoria as $values){
                        $nombre[] = ($values['nombre']);
                        $cantidad2[] = intval($values['cantidad2']);
                    }
                    echo
                    Highcharts::widget([
                        'scripts' => ['modules'],
                        'options' => [
                            'chart' => ['type' => 'column'],
                            'title' => ['text' => 'Productos más vendidos'],
                            'xAxis' => ['categories' => $nombre],
                            'yAxis' => ['title' => ['text' => 'Cantidad']],
                            'series' => [
                                [
                                   'name' => 'Productos',
                                   'color' => ' #3498db ',
                                   'colorByPoint' => false,
                                    'data' => $cantidad2,
                                ],
                            ],
                        ],
                    ]);
?>
        
        </div>
    <div class="col-md-6">
      <?php
    foreach($grafEmbajadores as $values){
                        $nombre2[] = ($values['nombre2']);
                        $registros[] = intval($values['numeroregistros']);
                        $ventas[] = intval($values['numeroventas']);
                    }
                    echo
                    Highcharts::widget([
                        'scripts' => ['modules/exporting'],
                        'options' => [
                            'chart' => ['type' => 'column'],
                            'title' => ['text' => 'Rendimiento Embajadores'],
                            'xAxis' => ['categories' => $nombre2],
                            'yAxis' => ['title' => ['text' => 'Cantidad']],
                            'series' => [
                                [
                                   'name' => 'Ventas',
                                   'color' => '#FF74A6',
                                   'colorByPoint' => false,
                                   'data' => $ventas,
                                ],
                                
                                [
                                   'name' => 'Registros',
                                   'color' => '#2B908F',
                                   'colorByPoint' => false,
                                   'data' =>  $registros,
                                ],
                            ],
                        ],
                    ]);
?>
        </div>
  
    
 </div>

views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap4\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\bootstrap4\ActiveForm;
use yii\bootstrap4\Html;
use yii\captcha\Captcha;

$this->title = 'Soporte';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact container-fluid ">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Gracias por contactar con nosotros, en breves un tecnico resolvera sus dudas.
        </div>

        <p>
           
        </p>

    <?php else: ?>

        <p>
            Rellene este formulario para ponerse en contacto con el equipo de soporte.
        </p>

        <div class="row">
            <div class="col-6">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('ENVIAR', ['class' => 'btn btn-fondo2', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
            

    <?php endif; ?>
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/gestion.php
<?php
 
use yii\helpers\Html;
use yii\helpers\Url;

/* @var $this yii\web\View */

$this->title = 'Gestión';
?>


<div class="row">
    <div class="col-6 ">         
        <div class="card3 zoom coloresletrablanca container-fluid flex-shrink-0 ">                  
            <div class="paddfotos">                    
                <?= Html::a(Html::img('@web/images/logo/logoproductos.png', ['alt' => 'Imagen no encontrada', 'class' => ' imgcard']), ['productos/index']) ?>
            </div>
        </div>           
    </div>
    <div class="col-3">         
        <div class="card zoom paddfotos">
            <div class="">       
                <?= Html::a(Html::img('@web/images/logo/logocompras.png', ['alt' => 'Imagen no encontrada', 'class' => ' imgcard2']), ['compras/index']) ?>
            </div>
        </div>
    </div> 
    <div class="col-3">
        <div class="card zoom paddfotos">
            <div class="">                      
                <?= Html::a(Html::img('@web/images/logo/logoproveedores.png', ['alt' => 'Imagen no encontrada', 'class' => ' imgcard2']), ['proveedores/index']) ?>
            </div>
        </div>            
    </div> 
</div>
<div class="row">
    <div class="col-6 ">

        <div class="card3 zoom coloresletrablanca container-fluid flex-shrink-0 espaciocard paddfotos">

            <div class="">                  
                <?= Html::a(Html::img('@web/images/logo/logoclientes.png', ['alt' => 'Imagen no encontrada', 'class' => ' imgcard']), ['clientes/index']) ?>
            </div>
        </div>
    </div>
    <div class="col-3" style="margin-bottom: 43px;" >
        <div class="card zoom espaciocard paddfotos">
            <div class="">       
                <?= Html::a(Html::img('@web/images/logo/logoembajadores.png', ['alt' => 'Imagen no encontrada', 'class' => ' imgcard2']), ['embajadores/index']) ?>
            </div>
        </div>
    </div> 
    <div class="col-3" style="margin-bottom: 43px;">
        <div class="card zoom espaciocard paddfotos ">                
            <div class="">   
                <?= Html::a(Html::img('@web/images/logo/logocategorias.png', ['alt' => 'Imagen no encontrada', 'class' => ' imgcard2']), ['tipos/index']) ?>
            </div>
        </div>
    </div> 
</div>
</div

views/site/index.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use coderius\swiperslider\SwiperSlider;
use yii\bootstrap4\Alert;
//use module\user\assets\UserAsset;
use app\controllers\SiteController;

/* @var $this yii\web\View */
//UserAsset::register(Yii::$app->view);
$this->title = 'Mainstay';
?>
<div class="row">
    <div class="col-md-6  ">
        <div class="card3 zoom container-fluid flex-shrink-0  ">
            <div class="  paddfotos">   
<?= Html::a(Html::img('@web/images/logo/logogestion.png', ['alt' => 'Imagen no encontrada', 'class' => ' imgcard2']), ['site/gestion']) ?>
            </div>
        </div>
        <div class="separator">
        </div>
        <div class="padslider">
            <?=
            SwiperSlider::widget([
                'slides' => [
                    //Html::img('@web/images/fotosmainstay/slider1mst_1.png', ['alt' => 'Imagen no encontrada', 'class' => '']),
                    Html::img('@web/images/fotosmainstay/sliderfoto1.png', ['alt' => 'Imagen no encontrada', 'class' => '']),
                    Html::img('@web/images/fotosmainstay/fotoslider3.png', ['alt' => 'Imagen no encontrada', 'class' => '']),
                    Html::img('@web/images/fotosmainstay/fotoslider4.png', ['alt' => 'Imagen no encontrada', 'class' => '']),
                    Html::img('@web/images/fotosmainstay/fotoslider5.png', ['alt' => 'Imagen no encontrada', 'class' => '']),
                ],
                'options' => [
                    'styles' => [
                        SwiperSlider::CONTAINER => ["height" => "350px", "width" => "100%"],
                        SwiperSlider::SLIDE => ["text-align" => "center"],
                    ],
                ],
            ]);
            ?>
        </div>
    </div>
    <div class="col-md-6  ">
        <div class="card3 zoom container-fluid flex-shrink-0">
            <div class=" paddfotos">   
<?= Html::a(Html::img('@web/images/logo/logocdd.png', ['alt' => 'Imagen no encontrada', 'class' => 'imgcard2']), ['site/cdd']) ?> 
            </div>
        </div>
        <div class="card3  zoom container-fluid flex-shrink-0 espaciocard ">


            <div class=" paddfotos">   
<?= Html::a(Html::img('@web/images/logo/logoads_1.png', ['alt' => 'Imagen no encontrada', 'class' => 'imgcard2']), ['site/reglasstock3']) ?> 
            </div>
        </div>
    </div>
</div>

views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap4\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\bootstrap4\ActiveForm;
use yii\bootstrap4\Html;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Por favor rellene los siguientes campos para acceder a su usuario:</p>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'layout' => 'horizontal',
        'fieldConfig' => [
            'template' => "{label}\n{input}\n{error}",
            'labelOptions' => ['class' => 'col-lg-1 col-form-label mr-lg-3'],
            'inputOptions' => ['class' => 'col-lg-3 form-control'],
            'errorOptions' => ['class' => 'col-lg-7 invalid-feedback'],
        ],
    ]); ?>

        <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

        <?= $form->field($model, 'password')->passwordInput() ?>

        <?= $form->field($model, 'rememberMe')->checkbox([
            'template' => "<div class=\"offset-lg-1 col-lg-3 custom-control custom-checkbox \">{input} {label}</div>\n<div class=\"col-lg-8\">{error}</div>",
        ]) ?>

        <div class="form-group">
            <div class="offset-lg-1 col-lg-11">
                <?= Html::submitButton('Login', ['class' => 'btn btn-fondo3', 'name' => 'login-button']) ?>
            </div>
        </div>

    <?php ActiveForm::end(); ?>

  
</div>

views/site/manual.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;
/* @var $this yii\web\View */

$this->title = 'Manual de Uso';
?>

views/site/nostock.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
$this->title = 'Stock';
?>

<div class="container-fluid paddfotos paddbotones">
<?=   Html::a(Html::img('@web/images/fotosmainstay/nostock1.png', ['alt' => 'Imagen no encontrada', 'class' => ' imgcard2']), ['site/index'])?>
</div>